# Generated by Django 5.0.1 on 2024-01-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('cricsheet_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('key_api', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
